# reporting/docker-compose.yml
services:
  reporting:
    build: .
    ports:
      - "8082:8082" # Acc√®s au dashboard
    volumes:
      - ../data:/data
    networks:
      - serving_prod_net

networks:
  serving_prod_net:
    external: true
